nastassjas/bound

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_title.scss
- app/assets/stylesheets/config/_fonts.scss
> added fonts

- app/controllers/associations_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/missions_controller.rb
- app/models/association.rb
- app/models/booking.rb
- app/models/enrollment.rb
- app/models/mission.rb
- app/models/skill.rb
- app/models/user_skill.rb
- db/migrate/20190604095838_create_associations.rb
- db/migrate/20190604100248_create_enrollments.rb
- db/migrate/20190604100313_create_skills.rb
- db/migrate/20190604100631_create_missions.rb
- db/migrate/20190604100721_create_user_skills.rb
- db/migrate/20190604100746_create_bookings.rb
- db/schema.rb
- test/controllers/associations_controller_test.rb
- test/controllers/bookings_controller_test.rb
- test/controllers/missions_controller_test.rb
- test/models/association_test.rb
- test/models/booking_test.rb
- test/models/enrollment_test.rb
- test/models/mission_test.rb
- test/models/skill_test.rb
- test/models/user_skill_test.rb
> routes models controllers

- app/views/shared/_navbar.html.erb
> new correction nabvar

- app/controllers/associations_controller.rb
- app/controllers/charities_controller.rb
- app/models/charity.rb
- app/models/enrollment.rb
- app/models/mission.rb
- db/migrate/20190604095838_create_charities.rb
- db/migrate/20190604100248_create_enrollments.rb
- db/migrate/20190604100631_create_missions.rb
- db/schema.rb
changed model name from association to charity
> changed model name

- app/controllers/charities_controller.rb
- app/controllers/missions_controller.rb
- config/routes.rb
> changement charities

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/policies/application_policy.rb
> pundit init

- app/controllers/associations_controller.rb
- app/controllers/pages_controller.rb
> maj deleted asso

- app/models/project.rb
- config/routes.rb
- db/migrate/20190605102829_create_projects.rb
- db/migrate/20190605103007_add_project_id_to_missions.rb
- db/migrate/20190605110511_add_columns_to_projects.rb
- db/migrate/20190605111004_remove_columns_from_missions.rb
- db/schema.rb
- test/models/project_test.rb
please merge and pull out the new db version
> changes schema db

- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- test/controllers/projects_controller_test.rb
- test/policies/project_policy_test.rb
> new project controller

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/projects/home.html.erb
some corrections on the homepage
> added changes to hp

- app/assets/stylesheets/components/_form.scss
- app/views/devise/registrations/new.html.erb
> new checkboxes

- app/assets/stylesheets/components/_userdashboard.scss
- app/controllers/users_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/projects/show.html.erb
- app/views/users/show.html.erb
new correction on forms and dashboard
> Correctiondashboard

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/controllers/projects_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/project.rb
- app/views/projects/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20190606084817_add_coordinates_to_projects.rb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
map and markers upload in the projects' results page
please merge
> Resultsfront

- app/controllers/application_controller.rb
- app/controllers/charities_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/users_controller.rb
- app/policies/charity_policy.rb
- app/policies/project_policy.rb
- app/views/shared/_navbar.html.erb
> navbar + assign user/asso

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
> new changes

- app/controllers/bookings_controller.rb
- app/controllers/users_controller.rb
- app/models/mission.rb
- app/policies/booking_policy.rb
- app/views/projects/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/schema.rb
> changement dashboard

- app/controllers/charities_controller.rb
- app/controllers/projects_controller.rb
- app/policies/project_policy.rb
- app/views/projects/new.html.erb
> project creation authorizations done

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_map.scss
- app/views/projects/_infowindow.html.erb
- app/views/projects/index.html.erb
cards display fixed
map markers fixed
map modals created
please merge
> results display fixed

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/projects/home.html.erb
added some corrections to the hp
> Newchangeshp

- app/views/projects/home.html.erb
- db/seeds.rb
> changes seed and home

- app/controllers/projects_controller.rb
- app/javascript/components/search.js
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/views/projects/index.html.erb
- db/seeds.rb
index search bar modified 
please merge
> index search changes

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> navbarfooter

- app/assets/stylesheets/pages/_home.scss
- app/views/projects/home.html.erb
> correction svg all website

- app/controllers/charities_controller.rb
- app/views/charities/roulette.html.erb
> rouletteYAS YAS YAS

- app/assets/stylesheets/components/_detailmission.scss
- app/controllers/projects_controller.rb
- app/javascript/components/search.js
- app/javascript/plugins/init_mapbox.js
- app/views/projects/show.html.erb
> Bookingupdate

- app/assets/stylesheets/config/_fonts.scss
- app/views/shared/_navbar.html.erb
> navbar logo new

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
> added metatags

- config/meta.yml
> correction tag image

- app/javascript/plugins/wave.js
> without js

- app/javascript/plugins/wave.js
- app/views/projects/index.html.erb
deleted the more details on the all missions page
> deleted more details

- app/assets/stylesheets/components/_detailmission.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_popup.scss
- app/views/bookings/_popup.html.erb
updated the pop up on the show
> updated pop up

- app/assets/stylesheets/components/_detailmission.scss
- app/views/projects/show.html.erb
i have updated the show with yellow
> Newnewupdates

- app/assets/stylesheets/components/_detailmission.scss
- app/views/bookings/_confirmation.html.erb
- app/views/projects/show.html.erb
- app/views/users/show.html.erb
changed hover color on show and dashboard
> changed hovers color

- app/assets/stylesheets/components/_formlogin.scss
- app/assets/stylesheets/components/_popup.scss
- app/views/bookings/_popup.html.erb
> yellow button added

- app/assets/stylesheets/components/_formlogin.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/packs/application.js
- app/javascript/plugins/category_skill.js
- app/views/devise/registrations/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/projects/home.html.erb
> form correction

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/projects/home.html.erb
changement home correction content
> changes home responsive correction

- app/assets/stylesheets/components/_popup.scss
- app/views/bookings/_popup.html.erb
added calender
added whatsapp, twitter icon
> added icons + calender

- app/assets/stylesheets/components/_userdashboard.scss
- app/views/projects/show.html.erb
- app/views/users/show.html.erb
added the little trashbox and deleted the h
> added trash

- db/seeds.rb
> added seed

- db/seeds.rb
> 1seed deleted

- app/views/projects/show.html.erb
> problem resolved

- app/assets/stylesheets/components/_navbar.scss
- app/views/users/show.html.erb
> done dashboard

- app/assets/stylesheets/pages/_home.scss
- app/views/projects/home.html.erb
> home responsive

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_detailmission.scss
- app/assets/stylesheets/components/_formlogin.scss
- app/assets/stylesheets/components/_searchbar.scss
- app/views/devise/registrations/new.html.erb
- app/views/projects/_cards_index.html.erb
- app/views/projects/home.html.erb
- app/views/projects/index.html.erb
- app/views/projects/show.html.erb
- db/seeds.rb
changement home + show + index
> afterwards correction
